### PR TITLE
Add first iteration of the SharedPtr implementation

### PR DESCRIPTION
**Pull request by theodor96**

### CODE REVIEW

**Comment by IonutLascu** [comment]
I expect your object return my use_count like this
```
{
    SharedPtr<int> ptr {new int};
    SharedPtr<int> cpyPtr = ptr;
    ptr->getCountOfAliveInstances() // or something like that, to know the use_count 
}
```

**Comment by theodor96** [comment]
> I expect your object return my use_count like this
> 
> ```
> {
>     SharedPtr<int> ptr {new int};
>     SharedPtr<int> cpyPtr = ptr;
>     ptr->getCountOfAliveInstances() // or something like that, to know the use_count 
> }
> ```

Fair enough, addressed with [this commit.](https://github.com/theodor96/shared-ptr/pull/3/commits/0a7fb29d5e09aded8b89f4ad89e5784756af3d00)

**Review by IonutLascu — APPROVED** [review]

**Comment by IonutLascu** [comment]
I saw your SharedPtr implementation is covariant. It would be great if I could do upcast or downcast. I wish I could know what kind of object contain that smart pointer.

**Comment by theodor96** [comment]
> I saw your SharedPtr implementation is covariant. It would be great if I could do upcast or downcast. I wish I could know what kind of object contain that smart pointer.

I guess you mean something like the [`std::*_pointer_cast` functionality?](https://en.cppreference.com/w/cpp/memory/shared_ptr/pointer_cast)

Since this implementation uses a common management table for refcounting, it's even easier to implement those casts, without special member (or non-member) functions -- which is both good (in shorter and easier code), and bad (in less obvious mechanics).

[This commit](https://github.com/theodor96/shared-ptr/pull/3/commits/0165228361c960b347d3067b733378546007dc65) does it by reusing the same template constructor (that had previously been used only for constructing `SharedPtr<Base>` from a `SharedPtr<Derived>`). Now it can be used for any (upwards or downwards) cast, with or without an explicit `static_cast`. Maybe requiring the cast to be explicit would do away with the disadvantage of code mechanics being trickier and less obvious. But then again, we want constructs such as `SharedPtr<Base> x = MakeShared<Derived>()` to work out of the box, which wouldn't if the constructor were explicit. As always, it's a matter of trade-offs. I think I'd leave the library code as is and then enforce `static_cast`s in client code (where they would be deemed necessary, on a case by case basis) by means of coding style and code review. Let me know what you think of this design : ).

**Pull request merged**
